### ISSUE TITLE
make installation easier with docker and docker-compose

### ISSUE THREAD

**Issue by abdennour** [joshp23/YOURLS-OIDC#6]
hello guys and thanks for the great effort !

I would suggest to have docker-compose.yaml which shows how to use this plugin, build it, mount it to the main app (yourls).
why not running keycloak as container

Starter docker-compose.yaml

```yaml
version: '3.9'

services:
  plugin:
    image: composer:1.7
  yourls:
    # tag from: https://github.com/YOURLS/charts/blob/master/charts/yourls/Chart.yaml#L5
    image: yourls:1.8.1
  keycloak:
      image: quay.io/keycloak/keycloak:14.0.0
  db:
    image:  mysql:5.7

```

if i got more time, i can finish it and open PR. However, this should be good starter.
Please let me know if you need any support
